import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import { useEffect, useState } from "react";
import Scene from "../components/Scene";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CLUBTRAIN2023</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="root">
          <Canvas>
            <Scene />
          </Canvas>
        </div>
      </main>
    </div>
  );
}
